[package]
name = "rustychess"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[lib]
name = "rustychess"
path = "src/lib.rs"

[dependencies]
rand = "0.9.2"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

